
spring:
  datasource:
   url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${PingItDbName}
   username: ${PingItDbUser}
   password: ${PingItDbUserPw}
  jpa:
    hibernate:
      ddl-auto: ${PingItDdlAuto}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
